### ISSUE TITLE
Using actions/checkout@v1 downloading the repo source Everytime

### ISSUE THREAD

**Issue by manivel-nagarajan** [norio-nomura/action-swiftlint#30]
Is there any way we can speed up this process? Why `actions/checkout@v1` process is happening every time from scratch? Is there any way to fetch only changes and perform lint?

**Comment by alokc83** [comment]
@manivel-nagarajan  Checkout action is from github and that is how its works. There is no dedicated build server which keeps your source code. 
Remember with github actions you are abstraction all the build machines nuances.

**Comment by manivel-nagarajan** [comment]
It is faster with actions/checkout@v2
